### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by caizixian** [zjuyxy/google200#1]
十分感谢你的作品，太有用了！(现在在外面，不方便看代码)
1 Python的依赖库应该直接pip就可以了吧？Redis安装完要不要什么配置？
2 Redis的作用是什么？作缓存吗？如果是的话可不可以去除？
3 API Key该放在哪里呢？建议用一个常量储存。
4 结果页最好可以超过9页。
5 这套系统对资源占用大不大？一台512MB的KVM VPS能不能撑得住？建议写一个详细一点的安装教程，或者你可以向我简单介绍一下安装过程，我有时间的话Pull Request.
6 搜索结果以哪个Google为准 我对比了一下 发现不一样呀XD

**Comment by zjuyxy** [comment]
1. python的依赖库pip都可以安装
2. redis的作用是缓存，和保存最近的查询关键词，查询关键的次数排行榜，以及配置的key
3. api key放在redis里
4. 结果页google api 只支持这么多
5. 我的云主机是512内存，平时只用到150M，我开了20个服务器线程
6. 结果不一样是因为api的参数和官网略有不同

**Comment by caizixian** [comment]
@zjuyxy Redis安装完后要不要配置？API的参数有什么可以调整的吗？
Redis数据库没有使用过，key该如何添加呢？
总之建议写一个详细的安装教程。
十分感谢！
