### ISSUE TITLE
安装后的初始化

### ISSUE THREAD

**Issue by caizixian** [zjuyxy/google200#2]
Redis安装完后要不要配置？API的参数有什么可以调整的吗？
Redis数据库没有使用过，key该如何添加呢？
总之建议写一个详细的安装教程。
十分感谢！

**Comment by zjuyxy** [comment]
假设你在google申请的key为xxxx。
只要在redis里调用  lpush keys xxxx就好了。
因为每个key一天只有100次调用，你会申请多个key，那就都用lpush keys ... 加到redis就好了
其他的redis连接看你自己配置对应修改代码里的连接地址和短裤。没时间写详细的安装教程。redis，flask等的安装网上都有的，自己先搜索一下吧。

**Comment by caizixian** [comment]
@zjuyxy flask什么的我比较熟 因为有开发过 至于Redis的问题，我刚刚看了官方的Doc，基本了解了一些，因为之前一直都在用SQL数据库，有思维定势，现在慢慢熟悉了。
